# Pandas

A biblioteca Pandas é uma das mais populares e poderosas ferramentas para manipulação e análise de dados em Python. Ela oferece estruturas de dados flexíveis, como DataFrames, que permitem organizar, limpar, transformar e explorar grandes volumes de dados de forma intuitiva. Com Pandas, é possível realizar operações como filtragem, agregação e fusão de dados com facilidade, sendo indispensável em qualquer fluxo de trabalho analítico.

## Introdução à Biblioteca Pandas

Documentação oficial: [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/getting_started/overview.html)

### Tipos de Dados que o Pandas Suporta

O Pandas é adequado para muitos formatos e tipos de dados, incluindo:

- Dados tabulares com colunas de tipos heterogêneos (como planilhas Excel ou tabelas SQL)

- Dados de séries temporais (ordenadas ou não, com ou sem frequência fixa)

- Matrizes com rótulos de linha e coluna, homogêneas ou heterogêneas

- Conjuntos de dados estatísticos ou observacionais (mesmo sem rótulos explícitos)

### Principais Funcionalidades do Pandas

- Manipulação fácil de dados ausentes, tanto para valores float quanto de outros tipos

- Mutabilidade de tamanho: é possível inserir ou remover colunas de um DataFrame ou objetos de dimensão superior com facilidade

- Agrupamento poderoso de dados, permitindo operações do tipo:

    - Divisão-aplicação-combinação

    - Agregações

    - Transformações

- Conversão facilitada de dados irregulares ou com indexações diferentes (de estruturas como listas, dicionários ou arrays NumPy) para objetos DataFrame

- Junção intuitiva de conjuntos de dados, útil para mesclar ou combinar informações de fontes distintas

- Remodelagem e criação de pivôs de dados de forma flexível, possibilitando reorganizar a estrutura de tabelas

- Rotulagem hierárquica de eixos, permitindo múltiplos níveis de índices (MultiIndex) nas linhas ou colunas

- Ferramentas robustas de leitura e escrita de arquivos, suportando diversos formatos como:

    - Arquivos de texto (CSV e delimitados)

    - Arquivos do Excel

    - Bancos de dados

    - Outros formatos estruturados

- Funcionalidades específicas para séries temporais, incluindo:

    - Geração de intervalos de datas

    - Conversão de frequência de dados

    - Estatísticas de janelas móveis

    - Deslocamento e atraso de datas

## DataFrame

Um DataFrame transforma dados brutos do Python, como dicionários, em uma estrutura tabular organizada (linhas e colunas), podendo também representar arquivos de tabela, como CSV ou Excel.

- É uma estrutura bidimensional: possui linhas e colunas.

- As colunas podem conter tipos de dados diferentes (como strings, inteiros, etc.).

- As colunas do DataFrame são do tipo Série, onde cada coluna é uma Série, e o conjunto de Séries forma o DataFrame.

- Pode ser manipulado como um array (pelos índices) ou como um dicionário (pelos nomes das colunas).

In [ ]:
import pandas as pd

# Exemplo 1: Transformando um dicionário em DataFrame

informacoes = { # dicionário
    "Nome": [
        "Felipe Orlando",
        "Lucas Kataque",
        "Pedro Juliane",
        "Rafael Monteiro"
    ],
    "Salario": [2600, 4300, 5400, 3100],
    "Profissao": ["Mecânico", "Engenheiro", "Médico", "Químico"]
}

df = pd.DataFrame(informacoes) # criar o nosso DataFrame
df

              Nome  Salario   Profissao
0   Felipe Orlando     2600    Mecânico
1    Lucas Kataque     4300  Engenheiro
2    Pedro Juliane     5400      Médico
3  Rafael Monteiro     3100     Químico

In [5]:
import pandas as pd
# Exemplo 2: Transformando um arquivo em DataFrame

BASE = "dados/chocolate.csv" # variavel para a nossa base de dados
df = pd.read_csv(BASE) # para ler aquivo csv
df

,Company \n(Maker-if known),Specific Bean Origin\nor Bar Name,REF,Review\nDate,Cocoa\nPercent,Company\nLocation,Rating,Bean\nType,Broad Bean\nOrigin
0,A. Morin,Agua Grande,1876,2016,63%,France,3.75,,Sao Tome
1,A. Morin,Kpime,1676,2015,70%,France,2.75,,Togo
2,A. Morin,Atsane,1676,2015,70%,France,3.00,,Togo
3,A. Morin,Akata,1680,2015,70%,France,3.50,,Togo
4,A. Morin,Quilla,1704,2015,70%,France,3.50,,Peru
...,...,...,...,...,...,...,...,...,...
1790,Zotter,Peru,647,2011,70%,Austria,3.75,,Peru
1791,Zotter,Congo,749,2011,65%,Austria,3.00,Forastero,Congo
1792,Zotter,Kerala State,749,2011,65%,Austria,3.50,Forastero,India
1793,Zotter,Kerala State,781,2011,62%,Austria,3.25,,India
1794,Zotter,"Brazil, Mitzi Blue",486,2010,65%,Austria,3.00,,Brazil