# Lista de Exercícios sobre Pandas

### Exercício 1: Abrindo uma Base de Dados

Utilizando a biblioteca Pandas, realize as primeiras etapas para iniciar a análise de uma base de dados:

- Carregue a base de dados `chocolate.csv` que está dentro da pasta `dados`.

- Exiba as 5 primeiras e últimas linhas do DataFrame resultante.

In [7]:
# Resolução do Exercício:

# Importando a biblioteca Pandas
import pandas as pd

# Carregando a base de dados
BASE = 'dados/chocolate.csv'
df = pd.read_csv(BASE)
df.columns = df.columns.str.replace('\n', ' ', regex=True).str.strip() # Removendo \n da base de dados

# Imprimindo as 5 primeiras linhas
df.head()

,Company (Maker-if known),Specific Bean Origin or Bar Name,REF,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin
0,A. Morin,Agua Grande,1876,2016,63%,France,3.75,,Sao Tome
1,A. Morin,Kpime,1676,2015,70%,France,2.75,,Togo
2,A. Morin,Atsane,1676,2015,70%,France,3.00,,Togo
3,A. Morin,Akata,1680,2015,70%,France,3.50,,Togo
4,A. Morin,Quilla,1704,2015,70%,France,3.50,,Peru

In [9]:
# Imprimindo as 5 últimas linhas
df.tail()

,Company (Maker-if known),Specific Bean Origin or Bar Name,REF,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin
1790,Zotter,Peru,647,2011,70%,Austria,3.75,,Peru
1791,Zotter,Congo,749,2011,65%,Austria,3.00,Forastero,Congo
1792,Zotter,Kerala State,749,2011,65%,Austria,3.50,Forastero,India
1793,Zotter,Kerala State,781,2011,62%,Austria,3.25,,India
1794,Zotter,"Brazil, Mitzi Blue",486,2010,65%,Austria,3.00,,Brazil